### PR TITLE
[FIX] Moved images away from api

### PR DESCRIPTION
**Pull request by MayankMittal1**

### CODE REVIEW

**Comment by LiorAgnin** [comment]
@MayankMittal1 Can you run the lint script `npm run lint-fix`/ `yarn lint-fix`? Other than that LGTM.

**Review by LiorAgnin — CHANGES_REQUESTED** [review]
@MayankMittal1 Can you run the lint script npm run lint-fix/ yarn lint-fix? Other than that LGTM.

**Comment by MayankMittal1** [comment]
@LiorAgnin updated

**Review by LiorAgnin — APPROVED** [review]
LGTM!

**Pull request merged**
